### PR TITLE
Adds a max range to the arty

### PR DESCRIPTION
**Pull request by printer16**
Adds a max range to the arty of 800. It can still shoot from the top of the German base to the bridge and a bit further but no longer from German base--> Soviet base.

### CODE REVIEW

**Comment by kachnov** [comment]
I personally have to problem with germans firing in the soviet base if they can manage to get coords

@tylerh95 any comment on this

**Comment by printer16** [comment]
It's very very easy for a scout to just sneak by everyone to get the coords and get out.

**Comment by printer16** [comment]
For ref, the distance from very top of German base to below the bridge where Soviets usually set up is 452.

**Comment by kachnov** [comment]
what if the Kanonier sets up at the very edge of the German base? Will he be able to reach the bunker then?

This may work temporarily, but it doesn't take into account map changes

I personally think it would be a better idea to have groups of excluded areas based on where the arty is fired from. For example, if you are in any german base area, you are unable to reach any bunker area. Each area would have a variable to categorize it, such `var/artyzone = "farsouth"`

Also, I would check to see if this is compatible with the latest map since the german base isn't the same

**Comment by Wesreidau** [comment]
The ability of the artillery to hit the Soviet base will be crucial once the Soviet base is reorganized. With the present one-bunker layout, artillery is very powerful because it shells one point. If those shells had to be spread across multiple targets, it would be much powerful. I would not worry about the artillery piece's range. At absolute most, set the maximum range to let it fire from the train station to the Soviet base.

**Comment by tylerh95** [comment]
I'm sorta on the fence on this.

I agree with the sentiment of the PR, which is that shelling the soviet base sucks and can heavily unbalance the game. However, I don't know if this is the way to fix it because it just means they'll set up the artillery closer to the soviet base.

**Comment by kachnov** [comment]
I think the idea is that it becomes easy to murder the kanonier by forcing him to set up at the train

although with the new train station I wonder if it will be

**Comment by Zilenan91** [comment]
yeah if this would make the kanonier set up at the train station instead of the german base to arty stuff it'd be a good balancer because it's so much less untouchable.

**Comment by printer16** [comment]
> I think the idea is that it becomes easy to murder the kanonier by forcing him to set up at the train
Pretty much. I'll look into it on both maps and see about what you suggested as well.

**Comment by printer16** [comment]
Closing this for now.

**Pull request closed without merging**
