### PR TITLE
Balance change

### PR DESCRIPTION
**Pull request by printer16**
Swaps the damage on the Russian and Germans bullets as well as increases the Russian snipers scoped gun scoped-in accuracy to be better than the non-scoped default Kar98k german gun. Russians get less accurate guns so they should get more powerful bullets. Not how it is currently-- Where Germans get the best of both worlds in accuracy, and in damage.

### CODE REVIEW

**Comment by kachnov** [comment]
german guns aren't supposed to be more accurate
it's a bug

**Comment by printer16** [comment]
do you want me to close this then? I imagine you have a better idea of what needs to be what

**Comment by kachnov** [comment]
I'm planning to completely balance guns some time in the future. You're welcome to do so too. Until then, the current balance should be kept.

This is just my opinion though, see what the other devs have to say.

**Comment by printer16** [comment]
> Until then, the current balance should be kept.

There really isn't a balance though, germans have better accuracy+damage as it is, live on server?

**Comment by Wesreidau** [comment]
A policy of balancing weapons rifle to rifle leaves us with problems balancing submachine gun to submachine gun. It is better to accept the Germans having a stronger rifle and machine gun and the Russians having a stronger submachine gun and heavy machine gun, then allow players to pick terrain and tactics to their respective advantages.

**Comment by printer16** [comment]
This isn't balancing rifle to rifle. This is making the Germans have higher accuracy, (slightly) less powerful guns, and the Russians have low accuracy rifles.

**Comment by Harcourt1** [comment]
+1 from me but update bolt-action.dm to fit the new merge

**Comment by printer16** [comment]
Resolved the conflicts and gave the Mosin a scoped accuracy (It was killed off during the scope PR or something.)

**Comment by kachnov** [comment]
is it possible to add constants for russian/german damage and accuracy to make them less of a mess

**Comment by kachnov** [comment]
I'm probably just going to close this and do my own balance changes tonight

**Pull request closed without merging**
